spring.application.name=oversystem
server.port=8080

#tengo para mysql pero obviamente puede cambiar esto para oracle cambiando dependencias y esta parte
spring.datasource.url=your_connection
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect